spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/polyclinic
    username: postgres
    password: qnocks
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false